status = warn
name = orders-pipeline

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} %-5p [%c{1}] (%t) %m%n

rootLogger.level = info
rootLogger.appenderRef.console.ref = console

logger.app.name = io.github.leonardsibelius.orders
logger.app.level = debug
logger.app.additivity = false
logger.app.appenderRef.console.ref = console
